version: "3"
services:
    database:
        image: postgres:10.4
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data

    s3:
        image: minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - ./data:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: minio server /data --console-address ":9001"


    data_service:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            -   .env.list
        depends_on:
            - s3
            - database

volumes:
    db-data:


